spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/fourleavesshoe2
    username: root
    password: duc2112002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    username: voduc0100@gmail.com
    password: tvhnwfasjnjhbcro
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 955503971044-oo6d985jcqrn41hk31bc5ghasobipfl5.apps.googleusercontent.com
            client-secret: ${{ secrets.GOOGLE}}
          facebook:
            client-id: 1535863076974023
            client-secret: ${{ secrets.FACEBOOK}}
twilio:
  AccountSid: AC8c8c886543a259ef1c32a52428752846
  AuthToken: ${{ secrets.TWILIO}}
  phoneNumber: +14148009296
application:
  security:
    jwt:
      secret-key: f2f1035db6a255e7885838b020f370d702d4bb0f35a368f06ded1ce8e6684a27
      expiration: 36000000
    momo:
      access-key: mTCKt9W3eU1m39TW
      partner-code: MOMOLRJZ20181206
      secret-key: ${{ secrets.MOMO}}
    vnpay:
      vnp_TmnCode: X3VCO73C
      vnp_HashSecret: 70OXPPONL7XA9QR57L1QDWQVZPYC4L3U